# R Script to analyze and plot qRT information generated by two different plates of cells sorted for sGRP78+/-
# Install the proper packages
install.packages("dplyr")
install.packages("xlsx")
install.packages("ggplot2")
install.packages("plotrix")

# Load the packages
library(ggplot2)
library(xlsx)
library(dplyr)
library(plotrix)

# Bring in the proper data
setwd(dir = "Desktop")
setwd(dir = "Clay")
setwd(dir = "qRT")
setwd(dir = "SCAssay")
#file.path <- ("~Desktop/Clay/qRT/SCAssay/")
#negdf <- data.frame(read.csv(paste(file.path, "060816MCF7sGRP78-SCAssay_data.csv", sep=""), header = TRUE, sep = ",", stringsAsFactors = FALSE))
#posdf <- data.frame(read.csv(paste(file.path, "060716MCF7sGRP78+SCAssay_data.csv", sep=""), header = TRUE, sep = ",", stringsAsFactors = FALSE))
negdf <- data.frame(read.csv("060816MCF7sGRP78-SCAssay_data.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
posdf <- data.frame(read.csv("060716MCF7sGRP78+SCAssay_data.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))

# Get rid of unnecessary rows and assign others to names
nwells <- negdf[8:nrow(negdf),1]
ncells <- negdf[8:nrow(negdf),2]
ngenes <- negdf[8:nrow(negdf),3]
nct <- negdf[8:nrow(negdf),10]
pwells <- posdf[8:nrow(posdf),1]
pcells <- posdf[8:nrow(posdf),2]
pgenes <- posdf[8:nrow(posdf),3]
pct <- posdf[8:nrow(posdf),10]

# Create a data frame with those vectors
negdf <- data.frame(nwells, ncells, ngenes, nct)
negdf <- negdf[-97:-101,]
colnames(negdf) <- c("Wells", "Cell_Line", "Gene_Target", "CT")

posdf <- data.frame(pwells, pcells, pgenes, pct)
posdf <- posdf[-97:-101,]
colnames(posdf) <- c("Wells", "Cell_Line", "Gene_Target", "CT")

#First way to get 18S mean
#s18 <- filter(negdf, Gene_Target == "18S") 
#s18 <- s18[1:nrow(negdf),4]
#s18 <- s18[!is.na(s18)]
#s18 <- as.numeric(as.character(s18))
#s18 <- mean(s18)

#Second way to get 18S mean
#control1 <- negdf[1,4]
#control2 <- negdf[2,4]
#control1 <- as.numeric(as.character(control1))
#control2 <- as.numeric(as.character(control2))
#controlCT <- c(control1, control2)
#controlCT <- mean(controlCT)

# Getting 18S Mean
neg18s <- filter(negdf, Gene_Target=="18S")
pos18s <- filter(posdf, Gene_Target=="18S")
neg18s <- mean(as.numeric(as.character(neg18s$CT)))
pos18s <- mean(as.numeric(as.character(pos18s$CT)))

# Adjusting types in the data frame
negdf$CT <- as.numeric(as.character(negdf$CT))
posdf$CT <- as.numeric(as.character(posdf$CT))

# Calculations inside the data frame to generate Delta CT and Delta Delta CT
negdf <- mutate(group_by(negdf, Gene_Target), avgct = mean(CT, na.rm = TRUE))
posdf <- mutate(group_by(posdf, Gene_Target), avgct = mean(CT, na.rm = TRUE))
negdf <- mutate(negdf, deltact = CT-neg18s)
posdf <- mutate(posdf, deltact = CT-pos18s)
negdf <- mutate(group_by(negdf, Gene_Target), avgdeltact = mean(deltact, na.rm = TRUE))
posdf <- mutate(group_by(posdf, Gene_Target), avgdeltact = mean(deltact, na.rm = TRUE))
negdf <- mutate(group_by(negdf, Gene_Target), deltadeltact = avgdeltact-deltact, na.rm = TRUE)
negdf <- mutate(group_by(negdf, Gene_Target), normalizedgeneexpression = 2^(-deltadeltact), na.rm = TRUE)
negdf <- mutate(group_by(negdf, Gene_Target), avgnormalized = mean(normalizedgeneexpression, na.rm = TRUE))

# Creating another temporary dataframe to make cross data frame calculations
tempdf <- data.frame(negdf$avgdeltact, posdf$deltact)
colnames(tempdf) <- c("navgdeltact", "pdeltact")
tempdf <- mutate(tempdf, deltadeltact = pdeltact-navgdeltact)

# Bringing in new Delta Delta CT calculations into data frame and changing the names
posdf <- data.frame(posdf, tempdf$deltadeltact)
names(posdf)[names(posdf) == 'tempdf.deltadeltact'] <- 'deltadeltact'

# Continuing calculations for gene expression
posdf <- mutate(group_by(posdf, Gene_Target), normalizedgeneexpression = 2^(-deltadeltact), na.rm = TRUE)
posdf <- mutate(group_by(posdf, Gene_Target), avgnormalized = mean(normalizedgeneexpression, na.rm = TRUE))

# Statistics on data
negdf <- mutate(group_by(negdf, Gene_Target), ddcSE = std.error(normalizedgeneexpression, na.rm = TRUE))
negdf <- mutate(group_by(negdf, Gene_Target), ddcSD = sd(normalizedgeneexpression, na.rm = TRUE))
posdf <- mutate(group_by(posdf, Gene_Target), ddcSE = std.error(normalizedgeneexpression, na.rm = TRUE))
posdf <- mutate(group_by(posdf, Gene_Target), ddcSD = sd(normalizedgeneexpression, na.rm = TRUE))

#Setting up data to plot
plotposdf <- posdf
plotposdf <- posdf[!duplicated(posdf$Gene_Target),]
#singleGT <- (!duplicated(posdf$Gene_Target))

# Plotting
ggplot(data = plotposdf) + 
    geom_bar(aes(x = Gene_Target, y = avgnormalized), stat = "identity", color = "blue") + 
    geom_errorbar(aes(x = Gene_Target, ymin = avgnormalized - ddcSE, ymax = avgnormalized + ddcSE)) +
    theme(plot.title = element_text(size = 10), axis.text.x = element_text(angle = 90, hjust = 1), axis.title.y = element_text(size = 7.5)) + 
    xlab("Gene Target") + 
    ylab("MCF7 sGRP78+ Relative Gene Expression to MCF7 sGRP78-") + 
    ggtitle("Relative Gene Expression of MCF7 sGRP78+ Cells Compared to MCF7 sGRP78-") 
    






###########
#Ideas

posdf <- mutate(group_by(posdf, Gene_Target), deltadeltact = posdf$deltact-negdf$avgdeltact, na.rm = TRUE)

posdf <- mutate(group_by(posdf, Gene_Target), normalizedgeneexpression = 2^(-deltdeltaact), na.rm = TRUE)

posdf <- posdf %>%
  group_by(Gene_Target) %>%
  rowwise() %>%
  mutate(deltadeltact = posdf$deltact-negdf[,7])


deltadeltact <- data.frame(posdf$deltact-negdf$avgdeltact)
posdf <- cbind(posdf, deltadeltact)



df1 

negdf <- negdf %>%
  group_by(Gene_Target) %>%
  summarise(avgCT = mean(CT), na.rm = TRUE)



#Grouping and averaging


posdf <- posdf %>%
            group_by(Gene_Target) %>%
            summarise(avgCT = mean(as.numeric(as.character(CT))), na.rm = TRUE)




