# R Script to analyze and plot qRT information generated by four different plates of cells treated with Dox or No Dox
# Install the proper packages
install.packages("dplyr")
install.packages("xlsx")
install.packages("ggplot2")
install.packages("plotrix")
install.packages("tidyverse")

# Load the packages
library(ggplot2)
library(xlsx)
library(dplyr)
library(plotrix)
library(tidyverse)

#Clean the data
tidydata <- function(x) {
  x <- x[,c("X96fast", "X", "X.7")]
  x <- x[-c(1:7),]
  splitcolumns <- str_split_fixed(x$X96fast, " ", 2)
  x <- cbind.data.frame(x, splitcolumns)
  x <- subset(x, select = -c(X96fast))
  colnames(x) <- c("Target", "CT", "Line", "Population")
  x$CT <- as.numeric(x$CT)
  x <- x[!is.na(x$CT),]
}

tidydata2 <- function(x) {
  x <- x[,c("X96fast", "X", "X.7")]
  x <- x[-c(1:7),]
  splitcolumns <- str_split_fixed(x$X96fast, " ", 3)
  x <- cbind.data.frame(x, splitcolumns)
  x <- subset(x, select = -c(X96fast, `2`))
  colnames(x) <- c("Target", "CT", "Line", "Population")
  x$CT <- as.numeric(x$CT)
  x <- x[!is.na(x$CT),]
}

#Isolate 18s mean
controlmean <- function(x) {
  x <- x %>%
    group_by(Target, Population) %>%
    mutate(meanCT = mean(CT, na.rm = TRUE))
}
# Bring in the proper data
setwd(dir = "Desktop")
setwd(dir = "Clay")
setwd(dir = "qRT")
setwd(dir = "SCAssay")
negGFPdf <- data.frame(read.csv("071816NCIsGRP78-SCAssay.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
posGFPdf <- data.frame(read.csv("071916NCIsGRP78+SCAssay.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
negRFPdf <- data.frame(read.csv("071816A549sGRP78-SCAssay.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
posRFPdf <- data.frame(read.csv("071816A549sGRP78+SCAssay.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))

# Get rid of unnecessary rows and assign others to names
negGFPdf <- tidydata(negGFPdf)
negRFPdf <- tidydata2(negRFPdf)
posGFPdf <- tidydata2(posGFPdf)
posRFPdf <- tidydata(posRFPdf)

#Isolate 18S mean
negGFPdf <- controlmean(negGFPdf)
negRFPdf <- controlmean(negRFPdf)
posGFPdf <- controlmean(posGFPdf)
posRFPdf <- controlmean(posRFPdf)

negGFPcontrolmeanCT <- negGFPdf[negGFPdf$Target == "18S",]
negRFPcontrolmeanCT <- negRFPdf[negRFPdf$Target == "18S",]
posGFPcontrolmeanCT <- posGFPdf[posGFPdf$Target == "18S",]
posRFPcontrolmeanCT <- posRFPdf[posRFPdf$Target == "18S",]

negGFPcontrolmeanCT <- negGFPcontrolmeanCT$meanCT[1]
negRFPcontrolmeanCT <- negRFPcontrolmeanCT$meanCT[1]
posGFPcontrolmeanCT <- posGFPcontrolmeanCT$meanCT[1]
posRFPcontrolmeanCT <- posRFPcontrolmeanCT$meanCT[1]

#Delta CT
negGFPdf <- negGFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-negGFPcontrolmeanCT)

negRFPdf <- negRFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-negRFPcontrolmeanCT)

posGFPdf <- posGFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-posGFPcontrolmeanCT)

posRFPdf <- posRFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-posRFPcontrolmeanCT)

#Average Delta CT
negGFPdf <- negGFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

negRFPdf <- negRFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

posGFPdf <- posGFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

posRFPdf <- posRFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

#Delta Delta CT
negGFPdf$Target <- as.factor(negGFPdf$Target)
uniquenegGFPdf <- filter(negGFPdf, !duplicated(Target))

negGFPdf$deltadeltaCT <- negGFPdf$deltaCT-uniquenegGFPdf$avgdeltaCT[match(negGFPdf$Target, uniquenegGFPdf$Target)]
posGFPdf$deltadeltaCT <- posGFPdf$deltaCT-uniquenegGFPdf$avgdeltaCT[match(posGFPdf$Target, uniquenegGFPdf$Target)]

negRFPdf$Target <- as.factor(negRFPdf$Target)
uniquenegRFPdf <- filter(negRFPdf, !duplicated(Target))

negRFPdf$deltadeltaCT <- negRFPdf$deltaCT-uniquenegRFPdf$avgdeltaCT[match(negRFPdf$Target, uniquenegRFPdf$Target)]
posRFPdf$deltadeltaCT <- posRFPdf$deltaCT-uniquenegRFPdf$avgdeltaCT[match(posRFPdf$Target, uniquenegRFPdf$Target)]

#Combine all the dataframes into 1 dataframe

totaldf <- rbind.data.frame(negGFPdf, posGFPdf, negRFPdf, posRFPdf)

totaldf <- totaldf %>%
  group_by(Line, Population, Target) %>%
  mutate(normalized = 2^(-deltadeltaCT))

totaldf <- totaldf %>%
  group_by(Line, Population, Target) %>%
  mutate(meannormalized = mean(normalized, na.rm=TRUE))

totaldf <- totaldf %>%
  group_by(Line, Population, Target) %>%
  mutate(SDnormalized = sd(normalized, na.rm=TRUE))

totaldf <- totaldf %>%
  group_by(Line, Population, Target) %>%
  mutate(SEnormalized = SDnormalized/sqrt(2))

write.csv(totaldf, "071816LungCancerSCAssay.csv")

#Setting up data to plot
plottotaldf <- totaldf[!duplicated(totaldf[,c("Target", "Population", "Line")]),]

# Plotting for bar graph
ggplot(plottotaldf) + 
    facet_wrap(~ Target, scales = "free") + 
    geom_bar(aes(x = Line, y = meannormalized, fill = Population), width = 0.5, stat = "identity", position = "dodge") + 
    geom_errorbar(aes(x = Line, ymin = meannormalized - SEnormalized, ymax = meannormalized + SEnormalized, fill = Population), width = .08, position = position_dodge(0.5)) +
    theme(plot.title = element_text(size = 10), 
          axis.text.x = element_text(size = 8), #hjust = 1, angle=90
          axis.title.y = element_text(size = 7.5))
    
# Plotting for Heat Map
ggplot(plottotaldf) + 
  facet_wrap(~ Line, scales = "free") + 
  geom_tile(aes(x = Population, y = Target, fill = meannormalized)) +  
  scale_fill_gradient(low = "white", high = "darkblue", name = "") + 
  xlab("") + 
  ylab("") + 
  theme(axis.text.x = element_text(size = 8), 
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 8)) 
