# R Script to analyze and plot qRT information generated by four different plates of cells treated with Dox or No Dox
# Install the proper packages
install.packages("dplyr")
install.packages("xlsx")
install.packages("ggplot2")
install.packages("plotrix")

# Load the packages
library(ggplot2)
library(xlsx)
library(dplyr)
library(plotrix)

# Bring in the proper data
file.path <- ("~/Desktop/Clay/qRT/")
negGFPdf <- data.frame(read.csv(paste(file.path, "Plate1060117MDAGFPNoDoxSCAssay.csv", sep=""), header = TRUE, sep = ",", stringsAsFactors = FALSE))
posGFPdf <- data.frame(read.csv(paste(file.path, "Plate1060517MDAGFP3d+DoxSCAssay.csv", sep=""), header = TRUE, sep = ",", stringsAsFactors = FALSE))
negRFPdf <- data.frame(read.csv(paste(file.path, "Plate1060617MDARFPNoDoxSCAssay.csv", sep=""), header = TRUE, sep = ",", stringsAsFactors = FALSE))
posRFPdf <- data.frame(read.csv(paste(file.path, "Plate2060617MDARFP3d+DoxSCAssay.csv", sep=""), header = TRUE, sep = ",", stringsAsFactors = FALSE))

qRTdata <- list(negGFPdf, posGFPdf, negRFPdf, posRFPdf)
# Get rid of unnecessary rows and assign others to names
tidydata <- function(x){
    x <- x[,c(2:3, 10)]
    x <- x[-c(1:7),]
    splitcolumns <- str_split_fixed(x$X96fast, " ", 4)
    x <- cbind.data.frame(x, splitcolumns)
    x <- subset(x, select = -c(X96fast, `1`, `4`))
    colnames(x) <- c("Target", "CT", "Population", "Txt")
    x$CT <- as.numeric(x$CT)
    x <- x[!is.na(x$CT),]
    #print(x)
}
tidydata(qRTdata)
#Isolate 18S mean
generatemean <- function(x) {
    x <- x %>%
    group_by(Target) %>%
    mutate(meanCT = mean(CT, na.rm = TRUE))
}



data <- list()
data <- lapply(qRTdata, function(x) tidydata(x))
data <- lapply(data, function(x) generatemean(x))
data <- 

negGFPcontrolmeanCT <- negGFPdf[negGFPdf$Target == "18S",]
negRFPcontrolmeanCT <- negRFPdf[negRFPdf$Target == "18S",]
posGFPcontrolmeanCT <- posGFPdf[posGFPdf$Target == "18S",]
posRFPcontrolmeanCT <- posRFPdf[posRFPdf$Target == "18S",]

negGFPcontrolmeanCT <- negGFPcontrolmeanCT$meanCT[1]
negRFPcontrolmeanCT <- negRFPcontrolmeanCT$meanCT[1]
posGFPcontrolmeanCT <- posGFPcontrolmeanCT$meanCT[1]
posRFPcontrolmeanCT <- posRFPcontrolmeanCT$meanCT[1]

#Delta CT
negGFPdf <- negGFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-negGFPcontrolmeanCT)

negRFPdf <- negRFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-negRFPcontrolmeanCT)

posGFPdf <- posGFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-posGFPcontrolmeanCT)

posRFPdf <- posRFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-posRFPcontrolmeanCT)

#Average Delta CT
negGFPdf <- negGFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

negRFPdf <- negRFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

posGFPdf <- posGFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

posRFPdf <- posRFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

#Delta Delta CT
negGFPdf$Target <- as.factor(negGFPdf$Target)
uniquenegGFPdf <- filter(negGFPdf, !duplicated(Target))

negGFPdf$deltadeltaCT <- negGFPdf$deltaCT-uniquenegGFPdf$avgdeltaCT[match(negGFPdf$Target, uniquenegGFPdf$Target)]
posGFPdf$deltadeltaCT <- posGFPdf$deltaCT-uniquenegGFPdf$avgdeltaCT[match(posGFPdf$Target, uniquenegGFPdf$Target)]

negRFPdf$Target <- as.factor(negRFPdf$Target)
uniquenegRFPdf <- filter(negRFPdf, !duplicated(Target))

negRFPdf$deltadeltaCT <- negRFPdf$deltaCT-uniquenegRFPdf$avgdeltaCT[match(negRFPdf$Target, uniquenegRFPdf$Target)]
posRFPdf$deltadeltaCT <- posRFPdf$deltaCT-uniquenegRFPdf$avgdeltaCT[match(posRFPdf$Target, uniquenegRFPdf$Target)]

#Combine all the dataframes into 1 dataframe

totaldf <- rbind.data.frame(negGFPdf, posGFPdf, negRFPdf, posRFPdf)

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(normalized = 2^(-deltadeltaCT))

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(meannormalized = mean(normalized, na.rm=TRUE))

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(SDnormalized = sd(normalized, na.rm=TRUE))

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(SEnormalized = SDnormalized/sqrt(2))

write.csv(totaldf, "060617MDADoxNoDoxSCAssay.csv")

#Setting up data to plot
plottotaldf <- totaldf[!duplicated(totaldf[,c("Target", "Population", "Txt")]),]

# Plotting for bar graph
ggplot(plottotaldf) + 
    facet_wrap(~ Target, scales = "free") + 
    geom_bar(aes(x = Population, y = meannormalized, fill = Txt), width = 0.5, stat = "identity", position = "dodge") + 
    geom_errorbar(aes(x = Population, ymin = meannormalized - SEnormalized, ymax = meannormalized + SEnormalized, fill = Txt), width = .08, position = position_dodge(0.5)) +
    theme(plot.title = element_text(size = 10), 
          axis.text.x = element_text(angle = 90, hjust = 1), 
          axis.title.y = element_text(size = 7.5))
