# R Script to analyze and plot qRT information generated by four different plates of cells treated with Dox or No Dox
# Install the proper packages
install.packages("dplyr")
install.packages("xlsx")
install.packages("ggplot2")
install.packages("plotrix")

# Load the packages
library(ggplot2)
library(xlsx)
library(dplyr)
library(plotrix)

# Bring in the proper data
setwd(dir = "Desktop")
setwd(dir = "Clay")
setwd(dir = "qRT")
negGFPdf <- data.frame(read.csv("Plate1052617MCF7GFPSCAssayNoDox.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
posGFPdf <- data.frame(read.csv("052917MCF7GFPSCASSAYDox.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
negRFPdf <- data.frame(read.csv("Plate1053017MCF7RFPNoDoxSCAssay.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
posRFPdf <- data.frame(read.csv("Plate2053017MCF7RFPDoxSCAssay.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))

# Get rid of unnecessary rows and assign others to names
negGFPdf <- negGFPdf[,c("X96fast", "X", "X.7")]
negGFPdf <- negGFPdf[-c(1:7),]
splitcolumns <- str_split_fixed(negGFPdf$X96fast, " ", 4)
negGFPdf <- cbind.data.frame(negGFPdf, splitcolumns)
negGFPdf <- subset(negGFPdf, select = -c(X96fast, `1`, `4`))
colnames(negGFPdf) <- c("Target", "CT", "Population", "Txt")
negGFPdf$CT <- as.numeric(negGFPdf$CT)
negGFPdf <- negGFPdf[!is.na(negGFPdf$CT),]

negRFPdf <- negRFPdf[,c("X96fast", "X", "X.7")]
negRFPdf <- negRFPdf[-c(1:7),]
splitcolumns <- str_split_fixed(negRFPdf$X96fast, " ", 4)
negRFPdf <- cbind.data.frame(negRFPdf, splitcolumns)
negRFPdf <- subset(negRFPdf, select = -c(X96fast, `1`, `4`))
colnames(negRFPdf) <- c("Target", "CT", "Population", "Txt")
negRFPdf$CT <- as.numeric(negRFPdf$CT)
negRFPdf <- negRFPdf[!is.na(negRFPdf$CT),]

posGFPdf <- posGFPdf[,c("X96fast", "X", "X.7")]
posGFPdf <- posGFPdf[-c(1:7),]
splitcolumns <- str_split_fixed(posGFPdf$X96fast, " ", 4)
posGFPdf <- cbind.data.frame(posGFPdf, splitcolumns)
posGFPdf <- subset(posGFPdf, select = -c(X96fast, `1`, `4`))
colnames(posGFPdf) <- c("Target", "CT", "Population", "Txt")
posGFPdf$CT <- as.numeric(posGFPdf$CT)
posGFPdf <- posGFPdf[!is.na(posGFPdf$CT),]

posRFPdf <- posRFPdf[,c("X96fast", "X", "X.7")]
posRFPdf <- posRFPdf[-c(1:7),]
splitcolumns <- str_split_fixed(posRFPdf$X96fast, " ", 4)
posRFPdf <- cbind.data.frame(posRFPdf, splitcolumns)
posRFPdf <- subset(posRFPdf, select = -c(X96fast, `1`, `4`))
colnames(posRFPdf) <- c("Target", "CT", "Population", "Txt")
posRFPdf$CT <- as.numeric(posRFPdf$CT)
posRFPdf <- posRFPdf[!is.na(posRFPdf$CT),]

#Isolate 18S mean
negGFPdf <- negGFPdf %>%
  group_by(Target) %>%
  mutate(meanCT = mean(CT, na.rm = TRUE))

negRFPdf <- negRFPdf %>%
  group_by(Target) %>%
  mutate(meanCT = mean(CT, na.rm = TRUE))

posGFPdf <- posGFPdf %>%
  group_by(Target) %>%
  mutate(meanCT = mean(CT, na.rm = TRUE))

posRFPdf <- posRFPdf %>%
  group_by(Target) %>%
  mutate(meanCT = mean(CT, na.rm = TRUE))

negGFPcontrolmeanCT <- negGFPdf[negGFPdf$Target == "18S",]
negRFPcontrolmeanCT <- negRFPdf[negRFPdf$Target == "18S",]
posGFPcontrolmeanCT <- posGFPdf[posGFPdf$Target == "18S",]
posRFPcontrolmeanCT <- posRFPdf[posRFPdf$Target == "18S",]

negGFPcontrolmeanCT <- negGFPcontrolmeanCT$meanCT[1]
negRFPcontrolmeanCT <- negRFPcontrolmeanCT$meanCT[1]
posGFPcontrolmeanCT <- posGFPcontrolmeanCT$meanCT[1]
posRFPcontrolmeanCT <- posRFPcontrolmeanCT$meanCT[1]

#Delta CT
negGFPdf <- negGFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-negGFPcontrolmeanCT)

negRFPdf <- negRFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-negRFPcontrolmeanCT)

posGFPdf <- posGFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-posGFPcontrolmeanCT)

posRFPdf <- posRFPdf %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-posRFPcontrolmeanCT)

#Average Delta CT
negGFPdf <- negGFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

negRFPdf <- negRFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

posGFPdf <- posGFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

posRFPdf <- posRFPdf %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

#Delta Delta CT
negGFPdf$Target <- as.factor(negGFPdf$Target)
uniquenegGFPdf <- filter(negGFPdf, !duplicated(Target))

negGFPdf$deltadeltaCT <- negGFPdf$deltaCT-uniquenegGFPdf$avgdeltaCT[match(negGFPdf$Target, uniquenegGFPdf$Target)]
posGFPdf$deltadeltaCT <- posGFPdf$deltaCT-uniquenegGFPdf$avgdeltaCT[match(posGFPdf$Target, uniquenegGFPdf$Target)]

negRFPdf$Target <- as.factor(negRFPdf$Target)
uniquenegRFPdf <- filter(negRFPdf, !duplicated(Target))

negRFPdf$deltadeltaCT <- negRFPdf$deltaCT-uniquenegRFPdf$avgdeltaCT[match(negRFPdf$Target, uniquenegRFPdf$Target)]
posRFPdf$deltadeltaCT <- posRFPdf$deltaCT-uniquenegRFPdf$avgdeltaCT[match(posRFPdf$Target, uniquenegRFPdf$Target)]

#Combine all the dataframes into 1 dataframe

totaldf <- rbind.data.frame(negGFPdf, posGFPdf, negRFPdf, posRFPdf)

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(normalized = 2^(-deltadeltaCT))

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(meannormalized = mean(normalized, na.rm=TRUE))

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(SDnormalized = sd(normalized, na.rm=TRUE))

totaldf <- totaldf %>%
  group_by(Population, Txt, Target) %>%
  mutate(SEnormalized = SDnormalized/sqrt(2))

write.csv(totalDF, "Plate1053017MCF7DoxNoDoxSCAssay.csv")

#Setting up data to plot
plottotaldf <- totaldf[!duplicated(totaldf[,c("Target", "Population", "Txt")]),]

# Plotting for bar graph
ggplot(plottotaldf) + 
    facet_wrap(~ Target, scales = "free") + 
    geom_bar(aes(x = Population, y = meannormalized, fill = Txt), width = 0.5, stat = "identity", position = "dodge") + 
    geom_errorbar(aes(x = Population, ymin = meannormalized - SEnormalized, ymax = meannormalized + SEnormalized, fill = Txt), width = .08, position = position_dodge(0.5)) +
    theme(plot.title = element_text(size = 10), 
          axis.text.x = element_text(angle = 90, hjust = 1), 
          axis.title.y = element_text(size = 7.5))
    






###########
#Ideas

posdf <- mutate(group_by(posdf, Gene_Target), deltadeltact = posdf$deltact-negdf$avgdeltact, na.rm = TRUE)

posdf <- mutate(group_by(posdf, Gene_Target), normalizedgeneexpression = 2^(-deltdeltaact), na.rm = TRUE)

posdf <- posdf %>%
  group_by(Gene_Target) %>%
  rowwise() %>%
  mutate(deltadeltact = posdf$deltact-negdf[,7])


deltadeltact <- data.frame(posdf$deltact-negdf$avgdeltact)
posdf <- cbind(posdf, deltadeltact)



df1 

negdf <- negdf %>%
  group_by(Gene_Target) %>%
  summarise(avgCT = mean(CT), na.rm = TRUE)



#Grouping and averaging


posdf <- posdf %>%
            group_by(Gene_Target) %>%
            summarise(avgCT = mean(as.numeric(as.character(CT))), na.rm = TRUE)




