# R Script to analyze and plot qRT information generated by four different plates of cells treated with Dox or No Dox
# Install the proper packages
install.packages("dplyr")
install.packages("xlsx")
install.packages("ggplot2")
install.packages("plotrix")

# Load the packages
library(ggplot2)
library(xlsx)
library(dplyr)
library(plotrix)

# Bring in the proper data
setwd(dir = "Desktop")
setwd(dir = "Clay")
setwd(dir = "qRT")
#datadf <- data.frame(read.csv("Plate1060917MCF7CSCsMSHitsEMT_data.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))
datadf <- data.frame(read.csv("Plate1062217MCF7sGRP78EMTTest_data.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))

# Get rid of unnecessary rows and assign others to names
datadf <- datadf[,c("X96fast", "X", "X.7")]
datadf <- datadf[-c(1:7),]
splitcolumns <- str_split_fixed(datadf$X96fast, " ", 2)
datadf <- cbind.data.frame(datadf, splitcolumns)
datadf <- subset(datadf, select = -c(X96fast, `1`))
colnames(datadf) <- c("Target", "CT", "Population")
datadf$CT <- as.numeric(datadf$CT)
datadf <- datadf[!is.na(datadf$CT),]

#Isolate 18S mean
datadf <- datadf %>%
  group_by(Target, Population) %>%
  mutate(meanCT = mean(CT, na.rm = TRUE))

csc <- as.data.frame(filter(datadf, Population == "sGRP78+"))
noncsc <- as.data.frame(filter(datadf, Population == "sGRP78-"))

csccontrolmeanCT <- csc[csc$Target == "18S",]
noncsccontrolmeanCT <- noncsc[noncsc$Target == "18S",]

csccontrolmeanCT <- csccontrolmeanCT$meanCT[1]
noncsccontrolmeanCT <- noncsccontrolmeanCT$meanCT[1]

#Delta CT
csc <- csc %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-csccontrolmeanCT)

noncsc <- noncsc %>%
  group_by(Target) %>%
  mutate(deltaCT = CT-noncsccontrolmeanCT)

#Average Delta CT
csc <- csc %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

noncsc <- noncsc %>%
  group_by(Target) %>%
  mutate(avgdeltaCT = mean(deltaCT, na.rm = TRUE))

#Delta Delta CT
noncsc$Target <- as.factor(noncsc$Target)
uniquenoncsc <- filter(noncsc, !duplicated(Target))

noncsc$deltadeltaCT <- noncsc$deltaCT-uniquenoncsc$avgdeltaCT[match(noncsc$Target, uniquenoncsc$Target)]
csc$deltadeltaCT <- csc$deltaCT-uniquenoncsc$avgdeltaCT[match(csc$Target, uniquenoncsc$Target)]

#Combine all the dataframes into 1 dataframe

cscDF <- rbind.data.frame(csc, noncsc)

cscDF <- cscDF %>%
  group_by(Population, Target) %>%
  mutate(normalized = 2^(-deltadeltaCT))

cscDF <- cscDF %>%
  group_by(Population, Target) %>%
  mutate(meannormalized = mean(normalized, na.rm=TRUE))

cscDF <- cscDF %>%
  group_by(Population, Target) %>%
  mutate(SDnormalized = sd(normalized, na.rm=TRUE))

cscDF <- cscDF %>%
  group_by(Population, Target) %>%
  mutate(SEnormalized = SDnormalized/sqrt(2))

write.csv(cscDF, "Plate1062217MCF7sGRP78EMTTest-Analyzed.csv")

#Setting up data to plot
plotcscDF <- cscDF[!duplicated(cscDF[,c("Target", "Population")]),]

# Plotting for bar graph
ggplot(plotcscDF) + 
    facet_wrap(~ Target, scales = "free") + 
    geom_bar(aes(x = Population, y = meannormalized, fill = Population), width = 0.5, stat = "identity", position = "dodge") + 
    geom_errorbar(aes(x = Population, ymin = meannormalized - SEnormalized, ymax = meannormalized + SEnormalized, fill = Population), width = .08, position = position_dodge(0.5)) +
    theme(plot.title = element_text(size = 10), 
          axis.text.x = element_text(angle = 90, hjust = 1), 
          axis.title.y = element_text(size = 7.5))
    

# Plotting for Heat Map
ggplot(plotcscDF) + 
  geom_tile(aes(x = Population, y = Target, fill = meannormalized)) +  
  scale_fill_gradient(low = "white", high = "royalblue", name = "") + 
  xlab("") + 
  ylab("") + 
  theme(axis.text.x = element_text(size = 8), 
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 8)) 

# Plotting for Marker Type
markerDF <- data.frame(read.csv("Plate1062217MCF7sGRP78EMTTest-Analyzed.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE))

epi <- filter(markerDF, Marker == "E")
mes <- filter(markerDF, Marker == "M")
ran <- filter(markerDF, Marker == "S")
con <- filter(markerDF, Marker == "C")

plotepi <- ggplot(epi) + 
  geom_tile(aes(x = Population, y = Target, fill = meannormalized)) +  
  scale_fill_continuous(limits=c(0, 4), breaks=seq(0,4,by=1),low='white',high='darkgreen') + 
  #scale_fill_gradient(trans = 'log', breaks = c(1, 2, 5, 10), low = "white", high = "darkgreen", name = "") + 
  ggtitle("Epithelial Markers") + 
  xlab("") + 
  ylab("") + 
  theme(axis.text.x = element_text(size = 10), 
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 8), 
        legend.title = element_text(size = 10)) 

plotmes <- ggplot(mes) + 
  geom_tile(aes(x = Population, y = Target, fill = meannormalized)) +  
  scale_fill_continuous(limits=c(0, 4), breaks=seq(0,4,by=1),low='white',high='darkgreen') + 
  #scale_fill_gradient(trans = 'log', breaks = c(1, 2, 5, 10), low = "white", high = "darkgreen", name = "") + 
  ggtitle("Mesenchymal Markers") + 
  xlab("") + 
  ylab("") + 
  theme(axis.text.x = element_text(size = 10), 
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10)) 

plotran <- ggplot(ran) + 
  geom_tile(aes(x = Population, y = Target, fill = meannormalized)) +  
  scale_fill_continuous(limits=c(0, 4), breaks=seq(0,4,by=1),low='white',high='darkgreen') + 
  #scale_fill_gradient(trans = 'log', breaks = c(1, 2, 5, 10), low = "white", high = "darkgreen", name = "") + 
  ggtitle("MS Markers") + 
  xlab("") + 
  ylab("") + 
  theme(axis.text.x = element_text(size = 10), 
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10))

plotcon <- ggplot(con) + 
  geom_tile(aes(x = Population, y = Target, fill = meannormalized)) +  
  scale_fill_continuous(limits=c(0, 4), breaks=seq(0,4,by=1),low='white',high='darkgreen') + 
  #scale_fill_gradient(trans = 'log', breaks = c(1, 2, 5, 10), low = "white", high = "darkgreen", name = "") + 
  ggtitle("Control Markers") + 
  xlab("") + 
  ylab("") + 
  theme(axis.text.x = element_text(size = 10), 
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10))

plot_grid(plotepi, plotmes, plotran, plotcon)
plot_grid(zz,yy)
